name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Executa a cada 6 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Gerar a animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: dougbt  # Substitua pelo seu nome de usuário
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Publicar o arquivo gerado
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
