name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Executa a cada 6 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Gerar a animação da cobrinha
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: dougbt
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
